[tool.ruff]

select = ["E", "F", "W", "C", "S", "I", "TCH", "N"]

# we need to check 'mood' of all docstrings, this needs to be enabled explicitly
extend-select = []

ignore = ["D100", "D101", "N802", "F821", "S105", "S311"]

target-version = "py311"
pydocstyle.convention = "google"
line-length = 100

[tool.coverage.report]
# unit tests fails if the total coverage measurement is under this threshold value
fail_under = 50
